# Generated by Django 5.2.2 on 2025-06-07 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='series/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='series.categoria')),
            ],
        ),
    ]
