# Generated by Django 3.2.25 on 2025-03-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
